services:
  nginx:
    image: nginx:latest
    container_name: nginx-web
    ports:
      - "80:80"
    labels:
      log_type: "nginx"
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
